# Path to an uncompressed FASTA file with all transcript sequences.
dna: Ref/ref_dna.fa
gtf: Ref/zma_chr.gtf
GenomeHisat2Index: Ref/ref_dna.fa

# Path to a folder where intermediate files will be written.
WorkDir: Result

# Path to a YAML file with samples and their corresponding FASTQ files.
SampleYaml: sample.yaml
